# Generated by Django 4.2.1 on 2023-06-22 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diarization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voice',
            old_name='AudioFile',
            new_name='audio_file',
        ),
    ]
